import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useI18n } from "@/hooks/useI18n";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { t } = useI18n();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <Link href="/dynamic/1">Go to page 1</Link>
          <Link href="/dynamic/2">Go to page 2</Link>
          <Link href="/dynamic/3">Go to page 3</Link>
          <Link href="/dynamic/4">Go to page 4 (shouldnt exist)</Link>
          <div></div>
        </div>

        <div className={styles.center}>
          <h2>{t("homepage.title")}</h2>
        </div>
      </main>
    </>
  );
}
